name: Install Qt

on: [push]

jobs:
  build:
    runs-on: windows-latest
    name: windows-latest - Qt 6.3.2
    env:
        CXXFLAGS: ${{ matrix.CXXFLAGS }}
        MAKEFLAGS: ${{ matrix.MAKEFLAGS }}
        QMAKE_MSC_VER: 16.11.31911.196
        CMAKE_PREFIX_PATH: $Qt6_DIR/lib/cmake
        CMAKE_CXX_FLAGS_DEBUG: "/g"

    steps:
      - name: Clone repo
        uses: actions/checkout@v2.3.4

      - name: Install Qt
        if: matrix.qt_version != 'system'
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: 6.3.2
          cache: true
      - name: Build with CMake
        if: startsWith('6.3.2', '6.')
        run: |
          mkdir build-cmake
          cd build-cmake
          cmake .. -D QT_DEFAULT_MAJOR_VERSION=6  -D CMAKE_CXX_FLAGS_DEBUG="/g"
          cmake --build .
      - name: Deploy
        run: |
          D:\a\ActionsTest\Qt\6.3.2\msvc2019_64\bin\windeployqt.exe --qmldir D:\a\ActionsTest\Qt\6.3.2\msvc2019_64\qml  D:\a\ActionsTest\ActionsTest\build-cmake\Debug\appuntitled11.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: |
            D:\a\ActionsTest\ActionsTest\build-cmake\Debug\

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ActionsTest
          tag_name: Version1
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
              GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: D:\a\ActionsTest\ActionsTest\build-cmake\Debug.zip
          asset_name: azblogfilter.windows-amd64.zip
          asset_content_type: application/zip






