name: Install Qt

on: [push]

jobs:
  build:
    runs-on: windows-latest
    name: ${{ matrix.platform }} - Qt ${{ matrix.qt_version }}
    env:
        CXXFLAGS: ${{ matrix.CXXFLAGS }}
        MAKEFLAGS: ${{ matrix.MAKEFLAGS }}
        QMAKE_MSC_VER: 16.11.31911.196
        CMAKE_PREFIX_PATH: $Qt6_DIR/lib/cmake
        CMAKE_CXX_FLAGS_DEBUG: ${{ matrix.CMAKE_CXX_FLAGS_DEBUG }}

    steps:
      - name: Clone repo
        uses: actions/checkout@v2.3.4

      - name: Install Qt
        if: matrix.qt_version != 'system'
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: 6.3.2
      - name: Build with CMake
        if: startsWith(6.3.2, '6.')
        run: |
          mkdir build-cmake
          cd build-cmake
          cmake .. -D QT_DEFAULT_MAJOR_VERSION=6  -D CMAKE_CXX_FLAGS_DEBUG="/g"
          cmake --build .




